---
title: "Aim 1 and 2"
author: "Nijia Ke"
date: "4/21/2021"
output: pdf_document
---

```{r warning=FALSE, message=FALSE}
library(imputeTS)
library(ggplot2)
library(PerformanceAnalytics)
library(ggpubr)
```

```{r warning=FALSE, message=FALSE}
otter = read.csv("otter2.csv", header = TRUE)

# impute the missing values for Altitude and store the values after imputation in a new variable called imp_Altitude
otter$imp_Altitude = c(na_kalman(otter$Altitude[1:20]), na_kalman(otter$Altitude[21:40]), na_kalman(otter$Altitude[41:60]), na_kalman(otter$Altitude[61:80]), na_kalman(otter$Altitude[81:100]))

#impute the missing values for Trout and store the values after imputation in a new variable called imp_Trout
otter$imp_Trout = c(na_kalman(otter$Trout[1:20]), na_kalman(otter$Trout[21:40]), na_kalman(otter$Trout[41:60]), na_kalman(otter$Trout[61:80]), na_kalman(otter$Trout[81:100]))

##use imp_Altitude and imp_Trout instead of Altitude and Trout for the rest of analysis!!!
```

*Include explanation of data processing methods and reasoning*

```{r}
# correlation matrix for the numerical variables
#corr.dat <- otter[c('imp_Altitude', 'imp_Trout', 'Caloric', 'Water.Excess', 'Amoeba', 'Water', 'Land')]
#chart.Correlation(corr.dat, histogram = TRUE)
```

```{r}
# correlation matrix for all the numerical variables, need to adjust the points to smaller sizes
corr.dat2 <- otter[c('Activity', 'imp_Altitude', 'imp_Trout', 'Caloric', 'Water.Excess', 'Amoeba', 'Water', 'Land', 'Month')]
chart.Correlation(corr.dat2, histogram = TRUE)
```

```{r}
#QQ-plots to check normality
qqnorm(otter$Activity)
qqline(otter$Activity) #right-skewed, use log transformation
qqnorm(otter$imp_Altitude)
qqline(otter$imp_Altitude) #right-skewed, use log transformation
qqnorm(otter$imp_Trout)
qqline(otter$imp_Trout) #right-skewed, use log transformation
qqnorm(otter$Caloric)
qqline(otter$Caloric)
qqnorm(otter$Water.Excess)
qqline(otter$Water.Excess) #water excess follows a normal distribution
qqnorm(otter$Amoeba)
qqline(otter$Amoeba)
qqnorm(otter$Water)
qqline(otter$Water)
qqnorm(otter$Land)
qqline(otter$Land) #right-skewed, potentially use log transformation
```



*Thomas can you add your code here for the plot that you made with each otter's activity over time?*

```{r}
ggplot(data =otter, aes(x = Month, y = Activity)) + geom_line(mapping = aes(colour = Otter)) + labs(title = "Activity Trends Over Time", caption = "Figure 1") + theme(plot.title = element_text(hjust = 0.5))

#after log transformation of Activity
ggplot(data =otter, aes(x = Month, y = log(Activity))) + geom_line(mapping = aes(colour = Otter)) + labs(title = "Logarithm of Activity Trends Over Time", caption = "Figure 2") + theme(plot.title = element_text(hjust = 0.5))
```

Preliminary findings: RO-599 is the only otter that has an obviously non-stationary trend
 - examined mean, variance, covariance
 - we may consider detrending or differencing just this otter
 

```{r warning=FALSE, message=FALSE}

## check the potential interaction of altitude, trout and amoeba with Otter by checking whether the slopes are parallel in the following three plots, all seem to be slightly unparallel

# plot of altitude affecting activity for each otter type after transformations
(alt.plot <- ggplot(otter, aes(x = log(imp_Altitude), y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Altitude and Activity by Otter Type', xlab = 'logarithm of Altitude', ylab = 'logarithm of Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of trout affecting activity for each otter type after transformations
(trout.plot <- ggplot(otter, aes(x = log(imp_Trout), y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Trout and Activity by Otter Type', xlab = 'logarithm of Trout', ylab = 'logarithm of Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of amoeba affecting activity for each otter type after tranformation
(amoeba.plot <- ggplot(otter, aes(x = Amoeba, y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Amoeba and Activity by Otter Type', xlab = 'Amoeba', ylab = 'Logarithm of Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

##The next four plots look like null plots, consistent with what we observed in the correlation matrix, we don't care about interactions

# plot of caloric affecting activity for each otter type after tranformation
(caloric.plot <- ggplot(otter, aes(x = Caloric, y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Caloric and Activity by Otter Type', xlab = 'Caloric', ylab = 'Logarithm of Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of water excess affecting activity for each otter type after transformation
(water.ex.plot <- ggplot(otter, aes(x = Water.Excess, y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Water Excess and Activity by Otter Type', xlab = 'Water Excess', ylab = 'Logarithm of Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of water affecting activity for each otter type after tranformation
(water.plot <- ggplot(otter, aes(x = Water, y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Water and Activity by Otter Type', xlab = 'Water', ylab = 'Logrithm of Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of Land affecting activity for each otter type after transformations
(alt.plot <- ggplot(otter, aes(x = log(Land+0.1), y = log(Activity))) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Land and Activity by Otter Type after tranformation', xlab = 'logarithm of Altitude', ylab = 'logarithm of Land') +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
# Possibly fix this line later to include all six plots together. For now, we can just use the chunk above.

#ggarrange(plotlist = alt.plot, trout.plot, caloric.plot, water.ex.plot, amoeba.plot, water.plot)
```

```{r}
#make transformation of variables
otter$lActivity = log(otter$Activity)
otter$lAltitude = log(otter$imp_Altitude)
otter$lTrout = log(otter$imp_Trout)
otter$lLand = log(otter$Land + 0.1)

otters.amoeba = subset(otter, !is.na(Amoeba))

otters.water = subset(otter, !is.na(Water))
```

```{r}
library(tseries)
library(MTS)
library(vars)
```

```{r}
otter = subset(otter, select = -c(Altitude, Trout, Lat., Long.))
```

```{r}
ro.599 = subset(otter, Otter == "RO-599")
ro.599 = subset(ro.599, select = -c(Otter, Site, Month, Month.1, Year, Water))
ro.918 = subset(otter, Otter == "RO-918")
ro.918 = subset(ro.918, select = -c(Otter, Site, Month, Month.1, Year))
ro.859 = subset(otter, Otter == "RO-859")
ro.859 = subset(ro.859, select = -c(Otter, Site, Month, Month.1, Year, Water))
ro.106 = subset(otter, Otter == "RO-106")
ro.106 = subset(ro.106, select = -c(Otter, Site, Month, Month.1, Year, Amoeba))
ro.255 = subset(otter, Otter == "RO-255")
ro.255 = subset(ro.255, select = -c(Otter, Site, Month, Month.1, Year, Amoeba))

ro.599.ts = ts(ro.599,
               frequency = 12,
               start = c(2018, 7))

ro.918.ts = ts(ro.918,
               frequency = 12,
               start = c(2018, 7))

ro.859.ts = ts(ro.859,
               frequency = 12,
               start = c(2018, 7))

ro.106.ts = ts(ro.106,
               frequency = 12,
               start = c(2018, 7))

ro.255.ts = ts(ro.255,
               frequency = 12,
               start = c(2018, 7))
```

```{r}
apply(ro.918.ts, 2, adf.test)
```

```{r}
ro.918.ts.stnry = diffM(ro.918.ts)

apply(ro.918.ts.stnry, 2, adf.test)
```

```{r}
plot.ts(ro.918.ts.stnry)
```

```{r}
var.918 = VAR(ro.918.ts.stnry,
              ic = "AIC",
              type = "none")

summary(var.918)
```

```{r}
library(TSA)
acf(otter$lActivity[1:20])
pacf(otter$lActivity[1:20])
acf(otter$lActivity[21:40])
pacf(otter$lActivity[21:40])
acf(otter$lActivity[41:60])
pacf(otter$lActivity[41:60])
acf(otter$lActivity[61:80])
pacf(otter$lActivity[61:80])
acf(otter$lActivity[81:100])
pacf(otter$lActivity[81:100])
```


```{r warning=FALSE, message=FALSE}
#otter 1 ~ AR(1)
arimax.model1 <- arima(otter$lActivity[1:20], order=c(1,0,0), include.mean=TRUE, method="CSS")
arimax.model1

acf(arimax.model1$residuals)
pacf(arimax.model1$residuals)
```

```{r}
#otter 2 ~ MA(1)
arimax.model2 <- arima(otter$lActivity[21:40], order=c(0,0,1), include.mean=TRUE, method="CSS")
arimax.model2

acf(arimax.model2$residuals)
pacf(arimax.model2$residuals)
```


```{r}
#otter 3 ~ MA(1)
arimax.model3 <- arima(otter$lActivity[41:60], order=c(0,0,1), include.mean=TRUE, method="CSS")
arimax.model3

acf(arimax.model3$residuals)
pacf(arimax.model3$residuals)
```


```{r}
#otter 4 ~ AR(1)
arimax.model4 <- arima(otter$lActivity[61:80], order=c(1,0,0), include.mean=TRUE, method="CSS")
arimax.model4

acf(arimax.model4$residuals)
pacf(arimax.model4$residuals)
```

```{r}
#otter 5 ~ MA(1)
arimax.model5 <- arima(otter$lActivity[81:100], order=c(0,0,1), include.mean=TRUE, method="CSS")
arimax.model5

acf(arimax.model5$residuals)
pacf(arimax.model5$residuals)
```



```{r}
library(nlme)
#model selection for otters.amoeba
#start from the full model m1.amb.ml
m1.amb.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Amoeba + Month + Site + lLand + lAltitude:Otter + lTrout:Otter + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m1.amb.ml)
AIC(update(m1.amb.ml, .~.-Amoeba:Otter))
AIC(update(m1.amb.ml, .~.-lTrout:Otter)) #choose this model for the 1st step
AIC(update(m1.amb.ml, .~.-lAltitude:Otter))

```

```{r}

# create a ML model without lTrout:Otter
m2.amb.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Amoeba + Month + Site + lLand + lAltitude:Otter + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m2.amb.ml)
AIC(update(m2.amb.ml, .~.-Amoeba:Otter))
AIC(update(m2.amb.ml, .~.-lAltitude:Otter)) #choose this model for the 2nd step 
```

```{r}

# create a ML model without lAltitude:Otter
m3.amb.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Amoeba + Month + Site + lLand + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m3.amb.ml)
AIC(update(m3.amb.ml, .~.-Amoeba:Otter)) #a high AIC, keep the Amoeba:Otter and its corresponding main effects

#In addition, check whether we should remove other main effects

AIC(update(m3.amb.ml, .~.-lAltitude))
AIC(update(m3.amb.ml, .~.-lTrout)) 
AIC(update(m3.amb.ml, .~.-Caloric)) 
AIC(update(m3.amb.ml, .~.-Water.Excess))
AIC(update(m3.amb.ml, .~.-Month))
AIC(update(m3.amb.ml, .~.-Site))
AIC(update(m3.amb.ml, .~.-lLand)) #choose this model for the 3rd step
```




```{r}
# create a ML model without lLand
m4.amb.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Amoeba + Month + Site + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m4.amb.ml)
AIC(update(m4.amb.ml, .~.-lAltitude))
AIC(update(m4.amb.ml, .~.-lTrout)) #choose this model for the 4th step
AIC(update(m4.amb.ml, .~.-Caloric)) 
AIC(update(m4.amb.ml, .~.-Water.Excess)) 
AIC(update(m4.amb.ml, .~.-Month))
AIC(update(m4.amb.ml, .~.-Amoeba:Otter))
AIC(update(m4.amb.ml, .~.-Amoeba))
AIC(update(m4.amb.ml, .~.-Site))
```

```{r}
# create a ML model without lTrout
m5.amb.ml = lme(lActivity ~ lAltitude + Caloric + Water.Excess + Amoeba + Month + Site + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m5.amb.ml)
AIC(update(m5.amb.ml, .~.-lAltitude))
AIC(update(m5.amb.ml, .~.-Caloric)) 
AIC(update(m5.amb.ml, .~.-Water.Excess)) #choose this model for the 5th step
#AIC(update(m5.amb.ml, .~.-Month))
AIC(update(m5.amb.ml, .~.-Amoeba:Otter))
AIC(update(m5.amb.ml, .~.-Amoeba))
#AIC(update(m5.amb.ml, .~.-Site)) 
```


```{r}
# create a ML model without Water.Excess
m6.amb.ml = lme(lActivity ~ lAltitude + Caloric + Amoeba + Month + Site + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m6.amb.ml)
AIC(update(m6.amb.ml, .~.-lAltitude))
AIC(update(m6.amb.ml, .~.-Caloric))
#AIC(update(m6.amb.ml, .~.-Month))
AIC(update(m6.amb.ml, .~.-Amoeba:Otter))
AIC(update(m6.amb.ml, .~.-Amoeba)) #The lowest AIC is reached, which is the same as in m5.amb.ml
AIC(update(m6.amb.ml, .~.-Site))
```


```{r}
m6.amb.reml = lme(lActivity ~ lAltitude + Caloric + Amoeba + Month + Site + Amoeba:Otter, random = ~1+Month|Otter, otters.amoeba)
#create a model using REML methods with intercept only

m7.amb.reml = lme(lActivity ~ lAltitude + Caloric + Amoeba + Month + Site + Amoeba:Otter, random = ~1|Otter, otters.amoeba)
lrtest(m6.amb.reml, m7.amb.reml)
#p=0.988, choose m7.amb.reml
```

```{r}
#compare with the linear regression model without random effect
m8.amb = lm(lActivity ~ lAltitude + Caloric + Amoeba + Month + Site + Amoeba:Otter, otters.amoeba)
lrt.1 = as.numeric(2*(logLik(m7.amb.reml) - logLik(m8.amb, REML = TRUE)))
# Since the fixed effects
#in both models are the same, we should use REML for both models to reduce bias
set.seed(2)
replic = 1000
lrstat = numeric(replic)
for(i in 1:replic){
rlActivity = unlist(simulate(m8.amb)) #generate a sample of simulated responses using the null model
#refit both models:
m8r= lm(lActivity ~ lAltitude + Caloric + Amoeba + Month + Site + Amoeba:Otter, otters.amoeba) 
m7r = lme(lActivity ~ lAltitude + Caloric + Amoeba + Month + Site + Amoeba:Otter, random = ~1|Otter, otters.amoeba)
lrstat[i] = 2*(logLik(m7r) - logLik(m8r, REML = TRUE))
}
mean(lrstat > lrt.1) #calculate the p-value = 0, random effect needs to be included
```


```{r}
summary(m7.amb.reml) 
qqnorm(residuals(m7.amb.reml))
qqline(residuals(m7.amb.reml))
plot(m7.amb.reml, which = 1)
```




```{r}
#model selection for otters.water
#start from the full model m1.wt.ml
m1.wt.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Water + Month + Site + lLand + lAltitude:Otter + lTrout:Otter, random = ~1+Month|Otter, method = "ML", otters.water)

AIC(m1.wt.ml)
#AIC(update(m1.wt.ml, .~.-lTrout:Otter)) 
AIC(update(m1.wt.ml, .~.-lAltitude:Otter)) #choose this model for the 1st step of model selection
```

```{r}
#remove lAltitude:Otter
m2.wt.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Water + Month + Site + lLand + lTrout:Otter, random = ~1+Month|Otter, method = "ML", otters.water)

AIC(m2.wt.ml)
#AIC(update(m2.wt.ml, .~.-lTrout:Otter))
AIC(update(m2.wt.ml, .~.-lAltitude))
#AIC(update(m2.wt.ml, .~.-lTrout))
AIC(update(m2.wt.ml, .~.-Caloric))
AIC(update(m2.wt.ml, .~.-Water.Excess)) #choose this model for the 2nd step of model selection
AIC(update(m2.wt.ml, .~.-Water))
#AIC(update(m2.wt.ml, .~.-Month))
#AIC(update(m2.wt.ml, .~.-Site)) 
AIC(update(m2.wt.ml, .~.-Land))
```


```{r}
#remove Water.Excess
m3.wt.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water + Month + Site + lLand + lTrout:Otter, random = ~1+Month|Otter, method = "ML", otters.water)

AIC(m3.wt.ml)
#AIC(update(m3.wt.ml, .~.-lTrout:Otter))
AIC(update(m3.wt.ml, .~.-lAltitude))
AIC(update(m3.wt.ml, .~.-lTrout))
AIC(update(m3.wt.ml, .~.-Caloric)) 
AIC(update(m3.wt.ml, .~.-Water))
#AIC(update(m3.wt.ml, .~.-Month))
#AIC(update(m3.wt.ml, .~.-Site))
AIC(update(m3.wt.ml, .~.-lLand)) #choose this model for the 3rd step of model selection
```

```{r}
#remove lLand
m4.wt.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water + Month + Site + lTrout:Otter, random = ~1+Month|Otter, method = "ML", otters.water)

AIC(m4.wt.ml)
#AIC(update(m4.wt.ml, .~.-lTrout:Otter))
AIC(update(m4.wt.ml, .~.-lAltitude))
AIC(update(m4.wt.ml, .~.-lTrout))
AIC(update(m4.wt.ml, .~.-Caloric)) #choose this model for the 4th step of model selection
AIC(update(m4.wt.ml, .~.-Water))
#AIC(update(m4.wt.ml, .~.-Month))
#AIC(update(m4.wt.ml, .~.-Site))
```



```{r}
#remove Water.Excess
m5.wt.ml = lme(lActivity ~ lAltitude + lTrout + Water + Month + Site + lTrout:Otter, random = ~1+Month|Otter, method = "ML", otters.water)

AIC(m5.wt.ml)
#AIC(update(m5.wt.ml, .~.-lTrout:Otter))
AIC(update(m5.wt.ml, .~.-lAltitude))
AIC(update(m5.wt.ml, .~.-lTrout))
AIC(update(m5.wt.ml, .~.-Water)) #choose this model for the 5th step of model selection
#AIC(update(m5.wt.ml, .~.-Month))
#AIC(update(m5.wt.ml, .~.-Site))
```




```{r}
#remove Water.Excess
m6.wt.ml = lme(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1+Month|Otter, method = "ML", otters.water)

AIC(m6.wt.ml)
#AIC(update(m6.wt.ml, .~.-lTrout:Otter))
AIC(update(m6.wt.ml, .~.-lAltitude))
AIC(update(m6.wt.ml, .~.-lTrout)) #AIC is the same as in m6.wt.ml, model selection of fixed effect is done
#AIC(update(m6.wt.ml, .~.-Month))
#AIC(update(m6.wt.ml, .~.-Site))

```

```{r}
m6.wt.reml = lme(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1+Month|Otter, otters.water)

m7.wt.reml = lme(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1|Otter, otters.water)

AIC(m6.wt.reml)
AIC(m7.wt.reml) #choose m7.wt.reml over m6.wt
```


```{r}
m8.wt = lm(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, otters.water)
lrt.1 = as.numeric(2*(logLik(m7.wt.reml) - logLik(m8.wt, REML = TRUE)))
# Since the fixed effects
#in both models are the same, we should use REML for both models to reduce bias
set.seed(2)
replic = 1000
lrstat = numeric(replic)
for(i in 1:replic){
rlActivity = unlist(simulate(m8.wt)) #generate a sample of simulated responses using the null model
#refit both models:
m8r= lm(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, otters.water) 
m7r = lme(rlActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1|Otter, otters.water)
lrstat[i] = 2*(logLik(m7r) - logLik(m8r, REML = TRUE))
}
mean(lrstat > lrt.1) #calculate the p-value = 0.515 > 0.05, random effect doesn't need to be included
```


```{r}
summary(m8.wt)
qqnorm(residuals(m8.wt))
qqline(residuals(m8.wt))
plot(m8.wt, which = 1)
```



```{r}
#build a model without including Amoeba and Water, using the complete dataset otter
m1.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Month + Site + lLand + lAltitude:Otter + lTrout:Otter, random = ~1+Month|Otter, otter, method = "ML")

BIC(m1.ml)
#BIC(update(m1.ml, .~.-lTrout:Otter)) 
BIC(update(m1.ml, .~.-lAltitude:Otter)) #choose this model for the 1st step
```


```{r}
#build a model without lAltitude:Otter 
m1.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Month + Site + lLand + lTrout:Otter, random = ~1+Month|Otter, otter, method = "ML")

BIC(m1.ml)
#BIC(update(m1.ml, .~.-lTrout:Otter)) 
BIC(update(m1.ml, .~.-lAltitude))
BIC(update(m1.ml, .~.-lTrout))
BIC(update(m1.ml, .~.-Caloric))
BIC(update(m1.ml, .~.-Water.Excess)) 
#BIC(update(m1.ml, .~.-Month))
#BIC(update(m1.ml, .~.-Site))
BIC(update(m1.ml, .~.-lLand)) #1st step of choice
```

```{r}
#build a model without lAltitude:Otter 
m2.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Water.Excess + Month + Site + lTrout:Otter, random = ~1+Month|Otter, otter, method = "ML")

BIC(m2.ml)
#BIC(update(m2.ml, .~.-lTrout:Otter)) 
BIC(update(m2.ml, .~.-lAltitude))
BIC(update(m2.ml, .~.-lTrout))
BIC(update(m2.ml, .~.-Caloric)) 
BIC(update(m2.ml, .~.-Water.Excess)) #2nd step of choice
#BIC(update(m2.ml, .~.-Month))
#BIC(update(m2.ml, .~.-Site))

```


```{r}
#build a model without lAltitude:Otter 
m3.ml = lme(lActivity ~ lAltitude + lTrout + Caloric + Month + Site + lTrout:Otter, random = ~1+Month|Otter, otter, method = "ML")

BIC(m3.ml)
#BIC(update(m3.ml, .~.-lTrout:Otter)) 
BIC(update(m3.ml, .~.-lAltitude))
BIC(update(m3.ml, .~.-lTrout))
BIC(update(m3.ml, .~.-Caloric)) #3rd step of choice
#BIC(update(m3.ml, .~.-Month))
#BIC(update(m3.ml, .~.-Site))

```


```{r}
m4.ml = lme(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1+Month|Otter, otter, method = "ML")

BIC(m4.ml)
#BIC(update(m4.ml, .~.-lTrout:Otter)) 
BIC(update(m4.ml, .~.-lAltitude))
BIC(update(m4.ml, .~.-lTrout)) #model selection of fixed effects if done, BIC is the same as in m4.ml
#BIC(update(m4.ml, .~.-Month))
#BIC(update(m4.ml, .~.-Site))
```


```{r}
m4.reml = lme(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1+Month|Otter, otter)

m5.reml = lme(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1|Otter, otter)

lrtest(m4.reml, m5.reml) #pvalue =1, choose m5.reml
```


```{r}
#build a linear regression model without random effects for comparison
m6 = lm(lActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, otter)
lrt.1 = as.numeric(2*(logLik(m5.reml) - logLik(m6, REML = TRUE)))
# Since the fixed effects
#in both models are the same, we should use REML for both models to reduce bias
set.seed(2)
replic = 1000
lrstat = numeric(replic)
for(i in 1:replic){
rlActivity = unlist(simulate(m6)) #generate a sample of simulated responses using the null model
#refit both models:
m6r= lm(rlActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, otter) 
m5r = lme(rlActivity ~ lAltitude + lTrout + Month + Site + lTrout:Otter, random = ~1|Otter, otter)
lrstat[i] = 2*(logLik(m5r) - logLik(m6r, REML = TRUE))
}
mean(lrstat > lrt.1) #calculate the p-value = 0.304 > 0.05, random effect doesn't need to be included
```


```{r}
summary(m6)
qqnorm(residuals(m6))
qqline(residuals(m6))
plot(m6, which = 1)
```

### specific aim 2

```{r warning=FALSE, message=FALSE}
#line plots
ggplot(data =otter, aes(x = Month, y = Caloric)) + geom_line(mapping = aes(colour = Otter)) + labs(title = "Caloric Trends Over Time") + theme(plot.title = element_text(hjust = 0.5))

#scatterplot with trend lines
ggplot(data =otter, aes(x = Month, y = Caloric)) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) + labs(title = "Caloric Trends Over Time") + theme(plot.title = element_text(hjust = 0.5))

# plot of Water affecting Caloric for each otter type,  no need to include the interaction term of Water:Otter
(alt.plot <- ggplot(otter, aes(x = Water, y = Caloric)) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Water and Activity by Otter Type', xlab = 'Water', ylab = 'Caloric') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of Land affecting Caloric for each otter type, no need to include the interaction term of Land:Otter
(alt.plot <- ggplot(otter, aes(x = Land, y = Caloric)) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Land and Activity by Otter Type', xlab = 'Land', ylab = 'Caloric') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of Land affecting Caloric for each otter type after transformations, making it worse than without transformation, so use Land instead of log of Land for building models
(alt.plot <- ggplot(otter, aes(x = log(Land+0.1), y = Caloric)) + geom_point(mapping = aes(colour = Otter)) + geom_smooth(aes(colour = Otter), method = lm, se = FALSE) +
  labs(title = 'Land and Caloric by Otter Type after tranformation', xlab = 'Logrithm of Land', ylab = 'Caloric') +
  theme(plot.title = element_text(hjust = 0.5)))
```



```{r}
m1c.amb.ml = lme(Caloric ~ lActivity + lAltitude + lTrout + Water.Excess + Amoeba + Month + Site + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m1c.amb.ml)
AIC(update(m1c.amb.ml, .~.-lActivity))
AIC(update(m1c.amb.ml, .~.-lAltitude)) #choose this model for the 1st step
AIC(update(m1c.amb.ml, .~.-lTrout)) 
AIC(update(m1c.amb.ml, .~.-Water.Excess)) 
AIC(update(m1c.amb.ml, .~.-Amoeba))
AIC(update(m1c.amb.ml, .~.-Month))
AIC(update(m1c.amb.ml, .~.-Site)) 
#AIC(update(m1c.amb.ml, .~.-Land)) 

```




```{r}
m2c.amb.ml = lme(Caloric ~ lActivity + lTrout + Water.Excess + Amoeba + Month + Site + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m2c.amb.ml)
AIC(update(m2c.amb.ml, .~.-lActivity))
AIC(update(m2c.amb.ml, .~.-lTrout)) 
AIC(update(m2c.amb.ml, .~.-Water.Excess)) 
AIC(update(m2c.amb.ml, .~.-Amoeba))
AIC(update(m2c.amb.ml, .~.-Month)) #choose this model for the 2nd step
AIC(update(m2c.amb.ml, .~.-Site)) 
AIC(update(m2c.amb.ml, .~.-Land)) 

```



```{r}
m3c.amb.ml = lme(Caloric ~ lActivity + lTrout + Amoeba + Water.Excess + Site + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m3c.amb.ml)
AIC(update(m3c.amb.ml, .~.-lActivity))
AIC(update(m2c.amb.ml, .~.-lTrout))
AIC(update(m3c.amb.ml, .~.-Amoeba)) #choose this model for the 3rd step
AIC(update(m3c.amb.ml, .~.-Water.Excess))
AIC(update(m3c.amb.ml, .~.-Site)) 
#AIC(update(m3c.amb.ml, .~.-Land)) 

```



```{r}
m4c.amb.ml = lme(Caloric ~ lActivity + lTrout + Water.Excess + Site + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m4c.amb.ml)
AIC(update(m4c.amb.ml, .~.-lActivity))
AIC(update(m4c.amb.ml, .~.-lTrout)) #choose this model for the 4th step
AIC(update(m4c.amb.ml, .~.-Water.Excess))
AIC(update(m4c.amb.ml, .~.-Site)) 
#AIC(update(m4c.amb.ml, .~.-Land)) 

```


```{r}
m5c.amb.ml = lme(Caloric ~ lActivity + Water.Excess + Site + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m5c.amb.ml) 
AIC(update(m5c.amb.ml, .~.-lActivity))
AIC(update(m5c.amb.ml, .~.-Water.Excess))
AIC(update(m5c.amb.ml, .~.-Site)) #choose this model for the 5th step
#AIC(update(m5c.amb.ml, .~.-Land)) 
```


```{r}
m6c.amb.ml = lme(Caloric ~ lActivity + Water.Excess + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m6c.amb.ml) 
AIC(update(m6c.amb.ml, .~.-lActivity)) #choose this model for the 6th step
AIC(update(m6c.amb.ml, .~.-Water.Excess)) 
#AIC(update(m6c.amb.ml, .~.-Land)) 
```

```{r}
m7c.amb.ml = lme(Caloric ~ Water.Excess + Land, random = ~1+Month|Otter, otters.amoeba, method = "ML")

AIC(m7c.amb.ml) #the selected model considering fixed effects
AIC(update(m7c.amb.ml, .~.-Water.Excess)) 
AIC(update(m7c.amb.ml, .~.-Land)) 
```


```{r}
m7c.amb.reml = lme(Caloric ~ Water.Excess + Land, random = ~1+Month|Otter, otters.amoeba) #use REML for comparison of random effects
m8c.amb.reml = lme(Caloric ~ Water.Excess + Land, random = ~1|Otter, otters.amoeba) #build a model without random slope
lrtest(m7c.amb.reml, m8c.amb.reml) #pvalue = 1, choose the reduced model m8c.amb.reml
```



```{r}
m9c.amb = lm(Caloric ~ Water.Excess + Land, otters.amoeba)
lrt.1 = as.numeric(2*(logLik(m8c.amb.reml) - logLik(m9c.amb, REML = TRUE)))
# Since the fixed effects
#in both models are the same, we should use REML for both models to reduce bias
set.seed(2)
replic = 1000
lrstat = numeric(replic)
for(i in 1:replic){
rCaloric = unlist(simulate(m9c.amb)) #generate a sample of simulated responses using the null model
#refit both models:
m9cr = lm(rCaloric ~ Water.Excess + Land, otters.amoeba) 
m8cr = lme(rCaloric ~ Water.Excess + Land, random = ~1|Otter, otters.amoeba)
lrstat[i] = 2*(logLik(m8cr) - logLik(m9cr, REML = TRUE))
}
mean(lrstat > lrt.1) #calculate the p-value = 0.21 > 0.05, random effect doesn't need to be included
```


```{r}
summary(m9c.amb)
qqnorm(residuals(m9c.amb))
qqline(residuals(m9c.amb))
plot(m9c.amb, which = 1)
```




```{r}
m1c.wt.ml = lme(Caloric ~ lActivity + lAltitude + lTrout + Water.Excess + Water + Month + Site + Land, random = ~1+Month|Otter, otters.water, method = "ML")

AIC(m1c.wt.ml)
AIC(update(m1c.wt.ml, .~.-lActivity))
AIC(update(m1c.wt.ml, .~.-lAltitude))
AIC(update(m1c.wt.ml, .~.-lTrout)) #choose this model for the 1st step
AIC(update(m1c.wt.ml, .~.-Water.Excess))
AIC(update(m1c.wt.ml, .~.-Water)) 
AIC(update(m1c.wt.ml, .~.-Month))
AIC(update(m1c.wt.ml, .~.-Site)) 
AIC(update(m1c.wt.ml, .~.-Land)) 

```


```{r}
m2c.wt.ml = lme(Caloric ~ lActivity + lAltitude + Water.Excess + Water + Month + Site + Land, random = ~1+Month|Otter, otters.water, method = "ML")

AIC(m2c.wt.ml)
AIC(update(m2c.wt.ml, .~.-lActivity)) #choose this model for the 2nd step
AIC(update(m2c.wt.ml, .~.-lAltitude))
AIC(update(m2c.wt.ml, .~.-Site)) 
AIC(update(m2c.wt.ml, .~.-Water.Excess))
AIC(update(m2c.wt.ml, .~.-Water)) 
AIC(update(m2c.wt.ml, .~.-Month)) 
AIC(update(m2c.wt.ml, .~.-Land)) 

```


```{r}
m3c.wt.ml = lme(Caloric ~ lAltitude + Water.Excess + Water + Month + Site + Land, random = ~1+Month|Otter, otters.water, method = "ML")

AIC(m3c.wt.ml)
AIC(update(m3c.wt.ml, .~.-Site)) 
AIC(update(m3c.wt.ml, .~.-lAltitude))
AIC(update(m3c.wt.ml, .~.-Land)) 
AIC(update(m3c.wt.ml, .~.-Water.Excess))
AIC(update(m3c.wt.ml, .~.-Water)) 
AIC(update(m3c.wt.ml, .~.-Month)) #choose this model for the 3rd step

```



```{r}
m4c.wt.ml = lme(Caloric ~ lAltitude + Water.Excess + Water + Site + Land, random = ~1+Month|Otter, otters.water, method = "ML")

AIC(m4c.wt.ml)
AIC(update(m4c.wt.ml, .~.-lAltitude))  step
AIC(update(m4c.wt.ml, .~.-Site)) 
AIC(update(m4c.wt.ml, .~.-Water.Excess))
AIC(update(m4c.wt.ml, .~.-Water)) #choose this model for the 4th step
AIC(update(m4c.wt.ml, .~.-Land)) 

```

```{r}
m5c.wt.ml = lme(Caloric ~ lAltitude + Water.Excess + Site + Land, random = ~1+Month|Otter, otters.water, method = "ML")

AIC(m5c.wt.ml)
AIC(update(m5c.wt.ml, .~.-lAltitude)) 
AIC(update(m5c.wt.ml, .~.-Water.Excess))
AIC(update(m5c.wt.ml, .~.-Site)) #choose this model for the 5th step
AIC(update(m5c.wt.ml, .~.-Land)) 
```


```{r}
m6c.wt.ml = lme(Caloric ~ lAltitude + Water.Excess + Land, random = ~1+Month|Otter, otters.water, method = "ML")

AIC(m6c.wt.ml) #selected model before considering random effects
AIC(update(m6c.wt.ml, .~.-lAltitude)) 
AIC(update(m6c.wt.ml, .~.-Water.Excess))
AIC(update(m6c.wt.ml, .~.-Land)) 

```




```{r}
#compare models with or without random slope of Month
m6c.wt.reml = lme(Caloric ~ lAltitude + Water.Excess + Land, random = ~1+Month|Otter, otters.water) 
m7c.wt.reml = lme(Caloric ~ lAltitude + Water.Excess + Land, random = ~1|Otter, otters.water)
lrtest(m6c.wt.reml, m7c.wt.reml) #pvalue = 1, choose m7c.wt.reml
```






```{r}
m8c.wt = lm(Caloric ~ lAltitude + Water.Excess + Land, otters.water)
lrt.1 = as.numeric(2*(logLik(m7c.wt.reml) - logLik(m8c.wt, REML = TRUE)))
# Since the fixed effects
#in both models are the same, we should use REML for both models to reduce bias
set.seed(2)
replic = 1000
lrstat = numeric(replic)
for(i in 1:replic){
rCaloric = unlist(simulate(m8c.wt)) #generate a sample of simulated responses using the null model
#refit both models:
m8cr = lm(rCaloric ~ lAltitude + Water.Excess + Land, otters.water) 
m7cr = lme(rCaloric ~ lAltitude + Water.Excess + Land, random = ~1|Otter, otters.water)
lrstat[i] = 2*(logLik(m7cr) - logLik(m8cr, REML = TRUE))
}
mean(lrstat > lrt.1) #calculate the p-value = 0.49 > 0.05, random effect doesn't need to be included
```


```{r}
summary(m8c.wt)
qqnorm(residuals(m8c.wt))
qqline(residuals(m8c.wt))
plot(m8c.wt, which = 1)
```



```{r}
m1c.ml = lme(Caloric ~ lActivity + lAltitude + lTrout + Water.Excess + Month + Site + Land, random = ~1+Month|Otter, otter, method = "ML")

AIC(m1c.ml)
AIC(update(m1c.ml, .~.-lActivity))
AIC(update(m1c.ml, .~.-lAltitude))
AIC(update(m1c.ml, .~.-lTrout)) 
AIC(update(m1c.ml, .~.-Water.Excess)) 
AIC(update(m1c.ml, .~.-Month))
AIC(update(m1c.ml, .~.-Site)) #choose this model for the 1st step
AIC(update(m1c.ml, .~.-Land)) 
```


```{r}
m2c.ml = lme(Caloric ~ lActivity + lAltitude + lTrout + Water.Excess + Month + Land, random = ~1+Month|Otter, otter, method = "ML")

AIC(m2c.ml)
AIC(update(m2c.ml, .~.-lActivity)) #choose this model for the 2nd step
AIC(update(m2c.ml, .~.-lAltitude))
AIC(update(m2c.ml, .~.-lTrout)) 
AIC(update(m2c.ml, .~.-Water.Excess)) 
AIC(update(m2c.ml, .~.-Month))
AIC(update(m2c.ml, .~.-Land)) 
```


```{r}
m3c.ml = lme(Caloric ~ lAltitude + lTrout + Water.Excess + Month + Land, random = ~1+Month|Otter, otter, method = "ML")

AIC(m3c.ml)
AIC(update(m3c.ml, .~.-lAltitude))
AIC(update(m3c.ml, .~.-lTrout)) 
AIC(update(m3c.ml, .~.-Water.Excess)) 
AIC(update(m3c.ml, .~.-Month))  #choose this model for the 3rd step
AIC(update(m3c.ml, .~.-Land)) 
```



```{r}
m4c.ml = lme(Caloric ~ lAltitude + lTrout + Water.Excess + Land, random = ~1+Month|Otter, otter, method = "ML")

AIC(m4c.ml)
AIC(update(m4c.ml, .~.-lAltitude))
AIC(update(m4c.ml, .~.-lTrout)) #choose this model for the 4th step 
AIC(update(m4c.ml, .~.-Water.Excess))  
AIC(update(m4c.ml, .~.-Land)) 
```



```{r}
m5c.ml = lme(Caloric ~ lAltitude + Water.Excess + Land, random = ~1+Month|Otter, otter, method = "ML")

AIC(m5c.ml) #model selected before considering random effects
AIC(update(m5c.ml, .~.-lAltitude))
AIC(update(m5c.ml, .~.-Water.Excess)) 
AIC(update(m5c.ml, .~.-Land)) 
```



```{r}
m5c.reml = lme(Caloric ~ lAltitude + Water.Excess + Land, random = ~1+Month|Otter, otter)
m6c.reml = lme(Caloric ~ lAltitude + Water.Excess + Land, random = ~1|Otter, otter)
lrtest(m5c.reml, m6c.reml) #pvalue = 1, choose m6c.reml
```



```{r}
m7c = lm(Caloric ~ lAltitude + Water.Excess + Land, otter)
lrt.1 = as.numeric(2*(logLik(m6c.reml) - logLik(m7c, REML = TRUE)))
# Since the fixed effects
#in both models are the same, we should use REML for both models to reduce bias
set.seed(2)
replic = 1000
lrstat = numeric(replic)
for(i in 1:replic){
rCaloric = unlist(simulate(m7c)) #generate a sample of simulated responses using the null model
#refit both models:
m7cr = lm(rCaloric ~ lAltitude + Water.Excess + Land, otter)
m6cr = lme(rCaloric ~ lAltitude + Water.Excess + Land, random = ~1|Otter, otter)
lrstat[i] = 2*(logLik(m6cr) - logLik(m7cr, REML = TRUE))
}
mean(lrstat > lrt.1) #calculate the p-value = 0.677 > 0.05, random effect doesn't need to be included
```


```{r}
summary(m7c)
qqnorm(residuals(m7c))
qqline(residuals(m7c))
plot(m7c, which = 1)
```







