---
title: "Practicum-3-group-2"
author: "Nijia Ke, "
date: "4/18/2021"
output: pdf_document
---

```{r warning=FALSE, message=FALSE}
library(imputeTS)
library(ggplot2)
library(PerformanceAnalytics)
library(ggpubr)
```

```{r warning=FALSE, message=FALSE}
otter = read.csv("otter2.csv", header = TRUE)

# impute the missing values for Altitude and store the values after imputation in a new variable called imp_Altitude
otter$imp_Altitude = c(na_kalman(otter$Altitude[1:20]), na_kalman(otter$Altitude[21:40]), na_kalman(otter$Altitude[41:60]), na_kalman(otter$Altitude[61:80]), na_kalman(otter$Altitude[81:100]))

#impute the missing values for Trout and store the values after imputation in a new variable called imp_Trout
otter$imp_Trout = c(na_kalman(otter$Trout[1:20]), na_kalman(otter$Trout[21:40]), na_kalman(otter$Trout[41:60]), na_kalman(otter$Trout[61:80]), na_kalman(otter$Trout[81:100]))

##use imp_Altitude and imp_Trout instead of Altitude and Trout for the rest of analysis!!!
```

*Include explanation of data processing methods and reasoning*

```{r}
# correlation matrix for the numerical variables
corr.dat <- otter[c('imp_Altitude', 'imp_Trout', 'Caloric', 'Water.Excess', 'Amoeba', 'Water')]
chart.Correlation(corr.dat, histogram = TRUE)
```

*Thomas can you add your code here for the plot that you made with each otter's activity over time?*

```{r}
ggplot(data =otter, aes(x = Month, y = Activity)) + geom_line(mapping = aes(colour = Otter)) + labs(title = "Activity Trends Over Time", caption = "Figure 1") + theme(plot.title = element_text(hjust = 0.5))
```

Preliminary findings: RO-599 is the only otter that has an obviously non-stationary trend
 - examined mean, variance, covariance
 - we may consider detrending or differencing just this otter
 

```{r}
# plot of altitude affecting activity over time for each otter type
(alt.plot <- ggplot(otter, aes(x = imp_Altitude, y = Activity)) + geom_line(mapping = aes(colour = Otter)) +
  labs(title = 'Altitude and Activity by Otter Type', xlab = 'Altitude', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of trout affecting activity over time for each otter type
(trout.plot <- ggplot(otter, aes(x = imp_Trout, y = Activity)) + geom_line(mapping = aes(colour = Otter)) +
  labs(title = 'Trout and Activity by Otter Type', xlab = 'Trout', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of caloric affecting activity over time for each otter type
(caloric.plot <- ggplot(otter, aes(x = Caloric, y = Activity)) + geom_line(mapping = aes(colour = Otter)) +
  labs(title = 'Caloric and Activity by Otter Type', xlab = 'Caloric', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of water excess affecting activity over time for each otter type
(water.ex.plot <- ggplot(otter, aes(x = Water.Excess, y = Activity)) + geom_line(mapping = aes(colour = Otter)) +
  labs(title = 'Water Excess and Activity by Otter Type', xlab = 'Water Excess', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of amoeba affecting activity over time for each otter type
(amoeba.plot <- ggplot(otter, aes(x = Amoeba, y = Activity)) + geom_line(mapping = aes(colour = Otter)) +
  labs(title = 'Amoeba and Activity by Otter Type', xlab = 'Amoeba', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of water affecting activity over time for each otter type
(water.plot <- ggplot(otter, aes(x = Water, y = Activity)) + geom_line(mapping = aes(colour = Otter)) +
  labs(title = 'Water and Activity by Otter Type', xlab = 'Water', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
# Possibly fix this line later to include all six plots together. For now, we can just use the chunk above.

# ggarrange(plotlist = alt.plot, trout.plot, caloric.plot, water.ex.plot, amoeba.plot, water.plot)
```

```{r}
otters.amoeba = subset(otter, !is.na(Amoeba))

otters.water = subset(otter, !is.na(Water))

(amoeba.plot <- ggplot(otters.amoeba, aes(x = Amoeba, y = Activity)) + geom_line(mapping = aes(colour = Otter), stat = "summary_bin", binwidth = .1) +
  labs(title = 'Amoeba and Activity by Otter Type', xlab = 'Amoeba', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))

# plot of water affecting activity over time for each otter type
(water.plot <- ggplot(otters.water, aes(x = Water, y = Activity)) + geom_line(mapping = aes(colour = Otter), stat = "summary_bin", binwidth = .8) +
  labs(title = 'Water and Activity by Otter Type', xlab = 'Water', ylab = 'Activity') +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
library(tseries)
library(MTS)
library(vars)
```

```{r}
otter = subset(otter, select = -c(Altitude, Trout, Lat., Long.))
```

```{r}
ro.599 = subset(otter, Otter == "RO-599")
ro.599 = subset(ro.599, select = -c(Otter, Site, Month, Month.1, Year, Water))
ro.918 = subset(otter, Otter == "RO-918")
ro.918 = subset(ro.918, select = -c(Otter, Site, Month, Month.1, Year))
ro.859 = subset(otter, Otter == "RO-859")
ro.859 = subset(ro.859, select = -c(Otter, Site, Month, Month.1, Year, Water))
ro.106 = subset(otter, Otter == "RO-106")
ro.106 = subset(ro.106, select = -c(Otter, Site, Month, Month.1, Year, Amoeba))
ro.255 = subset(otter, Otter == "RO-255")
ro.255 = subset(ro.255, select = -c(Otter, Site, Month, Month.1, Year, Amoeba))

ro.599.ts = ts(ro.599,
               frequency = 12,
               start = c(2018, 7))

ro.918.ts = ts(ro.918,
               frequency = 12,
               start = c(2018, 7))

ro.859.ts = ts(ro.859,
               frequency = 12,
               start = c(2018, 7))

ro.106.ts = ts(ro.106,
               frequency = 12,
               start = c(2018, 7))

ro.255.ts = ts(ro.255,
               frequency = 12,
               start = c(2018, 7))
```

```{r}
apply(ro.918.ts, 2, adf.test)
```

```{r}
ro.918.ts.stnry = diffM(ro.918.ts)

apply(ro.918.ts.stnry, 2, adf.test)
```

```{r}
plot.ts(ro.918.ts.stnry)
```

```{r}
var.918 = VAR(ro.918.ts.stnry,
              ic = "AIC",
              type = "none")

summary(var.918)
```

```{r}
# RO-599 impulse response to altitude and trout
ro.599.ts.irf <- as.data.frame(ro.599.ts)
myvars.599 <- c('Activity', 'imp_Altitude', 'imp_Trout')
ro.599.ts.irf <- ro.599.ts.irf[myvars.599]

ro.599.ts.irf = ts(ro.599.ts.irf,
               frequency = 12,
               start = c(2018, 7))

ro.599.ts.irf <- diff(log(ro.599.ts.irf))
# plot(ro.599.ts.irf)

irf.mod.599 <- VAR(ro.599.ts.irf, p = 1, type = 'const')

feir.599.1 <- irf(irf.mod.599, impulse = 'imp_Altitude', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

feir.599.2 <- irf(irf.mod.599, impulse = 'imp_Trout', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

plot(feir.599.1)
plot(feir.599.2)
```

```{r}
# RO-106 impulse response to altitude and trout
ro.106.ts.irf <- as.data.frame(ro.106.ts)
myvars.106 <- c('Activity', 'imp_Altitude', 'imp_Trout')
ro.106.ts.irf <- ro.106.ts.irf[myvars.106]

ro.106.ts.irf = ts(ro.106.ts.irf,
               frequency = 12,
               start = c(2018, 7))

ro.106.ts.irf <- diff(log(ro.106.ts.irf))
# plot(ro.106.ts.irf)

irf.mod.106 <- VAR(ro.106.ts.irf, p = 1, type = 'const')

feir.106.1 <- irf(irf.mod.106, impulse = 'imp_Altitude', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

feir.106.2 <- irf(irf.mod.106, impulse = 'imp_Trout', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

plot(feir.106.1)
plot(feir.106.2)
```

```{r}
# RO-255 impulse response to altitude and trout
ro.255.ts.irf <- as.data.frame(ro.255.ts)
myvars.255 <- c('Activity', 'imp_Altitude', 'imp_Trout')
ro.255.ts.irf <- ro.255.ts.irf[myvars.255]

ro.255.ts.irf = ts(ro.255.ts.irf,
               frequency = 12,
               start = c(2018, 7))

ro.255.ts.irf <- diff(log(ro.255.ts.irf))
# plot(ro.255.ts.irf)

irf.mod.255 <- VAR(ro.255.ts.irf, p = 1, type = 'const')

feir.255.1 <- irf(irf.mod.255, impulse = 'imp_Altitude', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

feir.255.2 <- irf(irf.mod.255, impulse = 'imp_Trout', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

plot(feir.255.1)
plot(feir.255.2)
```

```{r}
# RO-918 impulse response to altitude and trout
ro.918.ts.irf <- as.data.frame(ro.918.ts)
myvars.918 <- c('Activity', 'imp_Altitude', 'imp_Trout')
ro.918.ts.irf <- ro.918.ts.irf[myvars.918]

ro.918.ts.irf = ts(ro.918.ts.irf,
               frequency = 12,
               start = c(2018, 7))

ro.918.ts.irf <- diff(log(ro.918.ts.irf))
# plot(ro.918.ts.irf)

irf.mod.918 <- VAR(ro.918.ts.irf, p = 1, type = 'const')

feir.918.1 <- irf(irf.mod.918, impulse = 'imp_Altitude', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

feir.918.2 <- irf(irf.mod.918, impulse = 'imp_Trout', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

plot(feir.918.1)
plot(feir.918.2)
```

```{r}
# RO-859 impulse response to altitude and trout
ro.859.ts.irf <- as.data.frame(ro.859.ts)
myvars.859 <- c('Activity', 'imp_Altitude', 'imp_Trout')
ro.859.ts.irf <- ro.859.ts.irf[myvars.859]

ro.859.ts.irf = ts(ro.859.ts.irf,
               frequency = 12,
               start = c(2018, 7))

ro.859.ts.irf <- diff(log(ro.859.ts.irf))
# plot(ro.859.ts.irf)

irf.mod.859 <- VAR(ro.859.ts.irf, p = 1, type = 'const')

feir.859.1 <- irf(irf.mod.859, impulse = 'imp_Altitude', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

feir.859.2 <- irf(irf.mod.859, impulse = 'imp_Trout', response = 'Activity',
             n.ahead = 10, ortho = FALSE, runs = 1000)

plot(feir.859.1)
plot(feir.859.2)
```









